Add log_as_list as a visible property to Logger block
nio-blocks/logger pull request #21
Opened 2018-03-21 22:43 UTC by jennyknuth

- add log_as_list
- create test for format
- format

2018-03-21 23:45 UTC, mattdodge approved these changes
This does seem useful, to log lists of signals as such. Any reason we don't just make this a default of `True`? I don't really see the need to add a new visible property to the block.

The only downside I can see is that individual signals would still get logged with a wrapped `[]` around them, but the code could be updated to prevent that as well. Or maybe we just want that to happen.

What do @hansmosh and @tyoungNIO think?

2018-03-22 15:50 UTC, jennyknuth commented
I agree. Since the order of signals logged is non-deterministic, you can get some pretty confusing/unintuitive output in the current logger panel. Not sure this is ever helpful. Lists make sense because this is what is actually happening. Much easier to debug, etc., with lists.

2018-03-26 23:13 UTC, mattdodge requested changes
This is great! To follow our standards for block specs, this would be a spec bump to 1.2 (could maybe even argue 2.0 but I think 1.2 is ok). So this block version should bump to 1.2.0

2018-03-26 23:46 UTC, mattdodge approved these changes

2018-03-26 23:47 UTC, merged